### ISSUE TITLE
Input process with very large alphabet

### ISSUE THREAD

**Issue by Spiros713** [ddarmon/transCSSR#2]
Not sure if this is really an issue and so apologies if this is a stupid question, but let's say that I have a time series with a very large emission alphabet so that I run out of letters and characters. If I understand correctly your code and examples, input sequence ("stringX") should be a string with no separation between symbols and thus I can not take my alphabet to be just integer numbers due to the issue of distinguishing one emission from the next. How would you handle such a situation with your code? Is it currently possible to encode the input alphabet (axs) as integers from 1 to N and then take the "stringX" to be some string with some separation symbol between emissions?  If it is not currently possible, do you think it would be easy to make the appropriate modifications in the code?  Thanks

**Comment by ddarmon** [comment]
As currently implemented, the transCSSR codebase relies heavily on strings to do all of the counting and transition determination using the strings as keys to dictionaries. This could in principle be done with tuples of integers as the keys, but that would require a substantial rewrite.

I'm curious what dataset you have in mind that would require an alphabet size larger than the number of regular and special characters available on a modern computer? Or is it more for the convenience of using an integer-encoded alphabet?

**Comment by Spiros713** [comment]
Thanks for the quick reply. Well, I have a number of features, each with a large number of emissions which I want to combine into a single feature with a larger alphabet, so that it fits to the framework of epsilon-machines/transducers. For example, let's say you have discretized weather data, past temperature, humidity etc and you want to forecast the temperature for the next day. If I combine the input data into one feature with a long alphabet then it explodes quickly and thus I need to encode possible inputs into integers

**Comment by ddarmon** [comment]
Ah, I see.

In that case, you may be better off working with continuous-state extensions of the computational mechanics formalism.

I know of at least two flavors, one by Nicolas Brodu and Jim Crutchfield:

https://team.inria.fr/comcausa/continuous-causal-states/

And one by Georg Goerg and Cosma Shalizi:

https://proceedings.mlr.press/v31/goerg13a.html

**Comment by Spiros713** [comment]
Thank you so much for the references!
